[package]
name = "sg2"
version = "0.11.0"
edition = "2021"

authors = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Definition and types for the SG2 interface"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/stargaze-contracts"
homepage = "https://stargaze.zone"

[dependencies]
serde = { version = "1.0.133", default-features = false, features = ["derive"] }
schemars = "0.8.8"
